import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "./components/navigation"

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col h-screen max-h-screen justify-between ${geistMono.variable} antialiased`}>
        <header className="top-0 flex flex-wrap gap-6 items-center justify-center p-4 w-screen">
          < Navigation />
        </header>
          {children}
        <footer className="bottom-0 flex flex-wrap gap-6 items-center justify-center p-4 w-screen">
          <a
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            href="/about"
          >
            ABOUT
          </a>
      </footer>
      </body>
    </html>
  );
}
